### ISSUE TITLE
[Bug] Embed More Images no longer seems to work.

### ISSUE THREAD

**Issue by ghost** [Knewest/embed-more-images#5]
Posting an avif file seems to show nothing again with the latest mosaic changes. 
![image](https://github.com/Knewest/embed-more-images/assets/162859043/11b0ff8f-e8a7-488f-8164-60b1f5225ebf)
![image](https://github.com/Knewest/embed-more-images/assets/162859043/4f4450b6-dda4-4317-981d-5db1820fc2c3)

**Comment by Knewest** [comment]
Sorry, I was very late to this. I'll address it now.

**Comment by Knewest** [comment]
Fixed in v1.8... Thank you for the wait.

https://github.com/Knewest/embed-more-images/releases/
